//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSoap.ProductosService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://productos.tarea.com/wsdl", ConfigurationName="ClienteSoap.ProductosService.ProductosPortType")]
    public interface ProductosPortType
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://productos.tarea.com/wsdl/RegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.RegistrarProductoResponse> RegistrarProductoAsync(ClienteSoap.ProductosService.RegistrarProductoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://productos.tarea.com/wsdl/ConsultarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.ConsultarProductoResponse> ConsultarProductoAsync(ClienteSoap.ProductosService.ConsultarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://productos.tarea.com/wsdl/ListarProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.ListarProductosResponse> ListarProductosAsync(ClienteSoap.ProductosService.ListarProductosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://productos.tarea.com/wsdl/ActualizarStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.ActualizarStockResponse> ActualizarStockAsync(ClienteSoap.ProductosService.ActualizarStockRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://productos.tarea.com/wsdl/CalcularValorInventario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.CalcularValorInventarioResponse> CalcularValorInventarioAsync(ClienteSoap.ProductosService.CalcularValorInventarioRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="http://productos.tarea.com/wsdl/EliminarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.EliminarProductoResponse> EliminarProductoAsync(ClienteSoap.ProductosService.EliminarProductoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarProductoRequest", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class RegistrarProductoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string categoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public RegistrarProductoRequest()
        {
        }
        
        public RegistrarProductoRequest(string codigo, string nombre, string categoria, decimal precio, int cantidad)
        {
            this.codigo = codigo;
            this.nombre = nombre;
            this.categoria = categoria;
            this.precio = precio;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarProductoResponse", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class RegistrarProductoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        public RegistrarProductoResponse()
        {
        }
        
        public RegistrarProductoResponse(bool estado, string mensaje)
        {
            this.estado = estado;
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarProductoRequest", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class ConsultarProductoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        public ConsultarProductoRequest()
        {
        }
        
        public ConsultarProductoRequest(string codigo)
        {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarProductoResponse", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class ConsultarProductoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string categoria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public ConsultarProductoResponse()
        {
        }
        
        public ConsultarProductoResponse(bool estado, string mensaje, string codigo, string nombre, string categoria, decimal precio, int cantidad)
        {
            this.estado = estado;
            this.mensaje = mensaje;
            this.codigo = codigo;
            this.nombre = nombre;
            this.categoria = categoria;
            this.precio = precio;
            this.cantidad = cantidad;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://productos.tarea.com/wsdl")]
    public partial class Producto
    {
        
        private string codigoField;
        
        private string nombreField;
        
        private string categoriaField;
        
        private decimal precioField;
        
        private int cantidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarProductosRequest", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class ListarProductosRequest
    {
        
        public ListarProductosRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarProductosResponse", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class ListarProductosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("productos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteSoap.ProductosService.Producto[] productos;
        
        public ListarProductosResponse()
        {
        }
        
        public ListarProductosResponse(ClienteSoap.ProductosService.Producto[] productos)
        {
            this.productos = productos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarStockRequest", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class ActualizarStockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        public ActualizarStockRequest()
        {
        }
        
        public ActualizarStockRequest(string codigo, int cantidad)
        {
            this.codigo = codigo;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarStockResponse", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class ActualizarStockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadActualizada;
        
        public ActualizarStockResponse()
        {
        }
        
        public ActualizarStockResponse(bool estado, string mensaje, int cantidadActualizada)
        {
            this.estado = estado;
            this.mensaje = mensaje;
            this.cantidadActualizada = cantidadActualizada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularValorInventarioRequest", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class CalcularValorInventarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        public CalcularValorInventarioRequest()
        {
        }
        
        public CalcularValorInventarioRequest(string codigo)
        {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcularValorInventarioResponse", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class CalcularValorInventarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal valorTotal;
        
        public CalcularValorInventarioResponse()
        {
        }
        
        public CalcularValorInventarioResponse(bool estado, string mensaje, string nombre, decimal precio, int cantidad, decimal valorTotal)
        {
            this.estado = estado;
            this.mensaje = mensaje;
            this.nombre = nombre;
            this.precio = precio;
            this.cantidad = cantidad;
            this.valorTotal = valorTotal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarProductoRequest", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class EliminarProductoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo;
        
        public EliminarProductoRequest()
        {
        }
        
        public EliminarProductoRequest(string codigo)
        {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarProductoResponse", WrapperNamespace="http://productos.tarea.com/wsdl", IsWrapped=true)]
    public partial class EliminarProductoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://productos.tarea.com/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje;
        
        public EliminarProductoResponse()
        {
        }
        
        public EliminarProductoResponse(bool estado, string mensaje)
        {
            this.estado = estado;
            this.mensaje = mensaje;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ProductosPortTypeChannel : ClienteSoap.ProductosService.ProductosPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProductosPortTypeClient : System.ServiceModel.ClientBase<ClienteSoap.ProductosService.ProductosPortType>, ClienteSoap.ProductosService.ProductosPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductosPortTypeClient() : 
                base(ProductosPortTypeClient.GetDefaultBinding(), ProductosPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProductosPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductosPortTypeClient.GetBindingForEndpoint(endpointConfiguration), ProductosPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductosPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductosPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ProductosService.RegistrarProductoResponse> RegistrarProductoAsync(ClienteSoap.ProductosService.RegistrarProductoRequest request)
        {
            return base.Channel.RegistrarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ProductosService.ConsultarProductoResponse> ConsultarProductoAsync(ClienteSoap.ProductosService.ConsultarProductoRequest request)
        {
            return base.Channel.ConsultarProductoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.ProductosService.ListarProductosResponse> ClienteSoap.ProductosService.ProductosPortType.ListarProductosAsync(ClienteSoap.ProductosService.ListarProductosRequest request)
        {
            return base.Channel.ListarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ProductosService.ListarProductosResponse> ListarProductosAsync()
        {
            ClienteSoap.ProductosService.ListarProductosRequest inValue = new ClienteSoap.ProductosService.ListarProductosRequest();
            return ((ClienteSoap.ProductosService.ProductosPortType)(this)).ListarProductosAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ProductosService.ActualizarStockResponse> ActualizarStockAsync(ClienteSoap.ProductosService.ActualizarStockRequest request)
        {
            return base.Channel.ActualizarStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ProductosService.CalcularValorInventarioResponse> CalcularValorInventarioAsync(ClienteSoap.ProductosService.CalcularValorInventarioRequest request)
        {
            return base.Channel.CalcularValorInventarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.ProductosService.EliminarProductoResponse> EliminarProductoAsync(ClienteSoap.ProductosService.EliminarProductoRequest request)
        {
            return base.Channel.EliminarProductoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductosPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductosPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/productos");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProductosPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.ProductosPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProductosPortTypeClient.GetEndpointAddress(EndpointConfiguration.ProductosPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProductosPort,
        }
    }
}
